name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 13, 16, 17]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt-hotspot'
        java-version: ${{ matrix.java }}
    - run: mvn clean install
    - uses: actions/upload-artifact@v4
      with:
        name: VoucherTopup
        path: target/VoucherTopup-*.jar
