name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 13, 16, 17]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: [ 'adopt', 'adopt-hotspot', 'adopt-openj9', 'temurin' ]
        java-version: ${{ matrix.java }}
        check-latest: true
        cache: 'maven'
    cache-dependency-path: 'pom.xml' # optional
    - run: java -version && mvn --version
    - run: mvn clean install
    - uses: actions/upload-artifact@v3
      with:
        name: VoucherTopup
        path: target/VoucherTopup-*.jar
 
