name: Maven Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt-hotspot'
        java-package: jdk

    - name: Build with Maven
      run: mvn clean install

    - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: VoucherTopup Artifact
          path: target/VoucherTopup-*.jar
          
