
name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        java: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        java-package: jdk
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: java -version && mvn --version
    - run: mvn clean install
    - uses: actions/upload-artifact@v3
      with:
        name: VoucherTopup
        path: target/VoucherTopup-*.jar
        if-no-files-found: error
        retention-days: 1095
